### PR TITLE
Upgrade eslint-config-sinon to latest

### PR DESCRIPTION
**Pull request by mroderick**
This PR upgrades `eslint-config-sinon` to latest and replaces #84 

#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm run lint`
1. Observe that there are no errors or warnings reported

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mantoni** [comment]
How is the jsdoc plugin related?

**Comment by mroderick** [comment]
> How is the jsdoc plugin related?

It is required in the latest `eslint-config-sinon`, which was added with this pr: https://github.com/sinonjs/eslint-config-sinon/pull/6

**Comment by mantoni** [comment]
> It is required in the latest eslint-config-sinon

If it's required, why is it not a dependency of `eslint-config-sinon` then?

**Review by mantoni — APPROVED** [review]

**Comment by mroderick** [comment]
> If it's required, why is it not a dependency of `eslint-config-sinon` then?

I'm working towards that :)

**Pull request merged**
